#!/bin/bash

# Script to receive a MELD file from a POST request and store
# for (temporary) web access, the link returned in response.
#
# Also creates a logfile entry for each file stored.
#
# Todo:
#
# 1. This has only been tested on Ubuntu and there are hardcoded 
# PATH strings
#
# 2. The .ttl RDF files are never removed, this is left to something else
#
# 3. The logfile isn't checked for length.
#
# David De Roure 1 January 2018.

source ./config

OUTDIR=$OUTPREFIX/meld
URLBASE="$URLPREFIX/meld"

# For redhat on thalassa
#OUTDIR=/var/www/html/meld
#URLBASE="http://beta.numbersintonotes.net/meld"
#PYTHON=/usr/bin/python2.7

# For ubuntu on demeter
#OUTDIR=/home/dder/www/NumbersIntoNotes/mei
#URLBASE="http://numbersintonotes.net/mei"
#PYTHON=/usr/bin/python2.7

# For MacOS on Dave's laptop
#OUTDIR=/Users/dave/Sites/midi
#URLBASE="http://localhost/~dave/midi"
#PYTHON=/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7

TMP=/tmp/nin$$
DATE=`/bin/date`

cd /tmp # work somewhere other than the live Web space

cat >> $OUTDIR/log.txt <<EOF
[$DATE]
Referer: $HTTP_REFERER
User Agent: $HTTP_USER_AGENT
IP Address: $REMOTE_ADDR
EOF

# Respond to GET request - this is used by Javascript in the client to 
# test the availability of the CGI script

if [ "$REQUEST_METHOD" == "GET" ]; then
    echo  GET request received >> $OUTDIR/log.txt
    echo Content-Type: text/html
    echo
    cat <<- EOF
	<!DOCTYPE html>
	<html>
	<title>Numbers Into Notes MEI</title>
	<body>
	<p>User Agent: $HTTP_USER_AGENT</p>
	<p>IP Address: $REMOTE_ADDR</p>
	</body>
	</html>
	EOF
    exit
fi

if [ "$REQUEST_METHOD" != "POST" ]; then
    echo  Only GET and POST methods supported >> $OUTDIR/log.txt
    echo 'Status: 405 Method Not Allowed'
    echo
    exit
fi

$PYTHON -c "import cgi, cgitb; form = cgi.FieldStorage(); print form.getvalue('meldtext')" > $TMP

# validate input

grep "http://beta.numbersintonotes.net/mei/" $TMP >> $OUTDIR/log.txt

UUID=`sed -n 's/.*\/mei\/\([0-9a-f-]*\).*$/\1/p' $TMP`

if [ -z ${UUID} ] ; then
    echo  Cannot find ID >> $OUTDIR/log.txt
    rm -f $TMP
    echo 'Status: 400 Bad Request'
    echo
    exit
fi

cp $TMP $OUTDIR/${UUID}.ttl

echo $UUID >> $OUTDIR/$IDS

echo $URLBASE/$UUID >> $OUTDIR/fragments.txt

rm -f $TMP

if [ ! -s $OUTDIR/${UUID}.ttl ] ; then
    echo  Creation of MELD file $OUTDIR/${UUID}.ttl failed >> $OUTDIR/log.txt
    echo 'Status: 400 Bad Request'
    echo
    exit
fi

echo Created $OUTDIR/${UUID}.ttl >> $OUTDIR/log.txt

# to return link

cat << EOF
Content-Type: text/html
Access-Control-Allow-Origin: *

<!DOCTYPE html>
<html>
<head>
<title>Numbers Into Notes - Link to MEI File</title>
</head>
<body>
<h1>Link to MELD File</h1>
<p><a href="$URLBASE/${UUID}" download>${UUID}</A> generated on $DATE</p>
</body>
</html>
EOF

echo Generated $URLBASE/${UUID}.ttl >> $OUTDIR/log.txt

exit 0

# return MELD ,ttl attachment for download

echo "Content-type: application/octet-stream"
echo "Content-disposition: attachment; filename=$UUID.ttl"
echo "Access-Control-Allow-Origin: *"
echo ""
cat $OUTDIR/${UUID}.ttl

exit 0

# End of meld
