#!/bin/bash

# Script to receive a PROV-N file from a POST request and convert it
# to an SVG File which is stored for (temporary) web access and
# the link returned in response.
#
# For now the source file is also stored, in case it is needed for debugging.
# 
# Also creates a logfile entry for each conversion.
#
# Todo:
#
# 1. This has only been tested on MacOS and Ubuntu and there are hardcoded 
# PATH strings
#
# 2. The .csv and .mid files are never removed, this is left to something else
#
# 3. The logfile isn't checked for length.
#
# David De Roure 15 February 2016

# For redhat on thalassa
OUTDIR=/var/www/html/prov
URLBASE="http://beta.numbersintonotes.net/prov"
CONVERT=/usr/local/bin/provconvert
PYTHON=/usr/bin/python2.7

# For ubuntu on demeter
#OUTDIR=/home/dder/www/NumbersIntoNotes/prov
#URLBASE="http://demeter.oerc.ox.ac.uk/NumbersIntoNotes/prov"
#CONVERT=/home/dder/ProvToolbox/bin/provconvert
#PYTHON=/usr/bin/python2.7

# For MacOS on Dave's laptop
#OUTDIR=/Users/dave/Sites/prov
#URLBASE="http://localhost/~dave/prov"
#CONVERT=/Users/dave/bin/prov
#PYTHON=/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7

TMP=/tmp/nin$$
DATE=`/bin/date`

cd /tmp # work somewhere other than the live Web space

cat >> $OUTDIR/log.txt <<EOF
[$DATE]
Referer: $HTTP_REFERER
User Agent: $HTTP_USER_AGENT
IP Address: $REMOTE_ADDR
EOF

# Respond to GET request - this is used by Javascript in the client to 
# test the availability of the CGI script

if [ "$REQUEST_METHOD" == "GET" ]; then
    echo  GET request received >> $OUTDIR/log.txt
    echo Content-Type: text/html
    echo
    cat <<- EOF
	<!DOCTYPE html>
	<html>
	<title>Numbers Into Notes PROV</title>
	<body>
	<p>User Agent: $HTTP_USER_AGENT</p>
	<p>IP Address: $REMOTE_ADDR</p>
	</body>
	</html>
	EOF
    exit
fi

if [ "$REQUEST_METHOD" != "POST" ]; then
    echo  Only GET and POST methods supported >> $OUTDIR/log.txt
    echo 'Status: 405 Method Not Allowed'
    echo
    exit
fi

$PYTHON -c "import cgi, cgitb; form = cgi.FieldStorage(); print form.getvalue('provtext')" > $TMP

# validate input
ls -l $TMP >> $OUTDIR/log.txt
cp $TMP $OUTDIR/foo

grep "NumbersIntoNotes ID " $TMP >> $OUTDIR/log.txt

UUID=`sed -n 's/^\/\/ NumbersIntoNotes ID \([0-9a-f-]*\)$/\1/p' $TMP`

if [ -z ${UUID} ] ; then
    echo  Cannot find ID >> $OUTDIR/log.txt
    rm -f $TMP
    echo 'Status: 400 Bad Request'
    echo
    exit
fi

cp $TMP $OUTDIR/${UUID}.provn
rm -f $TMP

if [ ! -s $OUTDIR/${UUID}.provn ] ; then
    echo  Creation of $OUTDIR/${UUID}.provn failed >> $OUTDIR/log.txt
    echo 'Status: 400 Bad Request'
    echo
    exit
fi

echo Created $OUTDIR/${UUID}.provn >> $OUTDIR/log.txt

echo "$CONVERT -infile $OUTDIR/${UUID}.provn -outfile $OUTDIR/${UUID}.svg -title $UUID" >> $OUTDIR/log.txt

$CONVERT -infile $OUTDIR/${UUID}.provn -outfile $OUTDIR/${UUID}.svg -title $UUID 2>> $OUTDIR/log.txt

if [ $? -gt 0 ] ;  then
    echo $CONVERT returned $? >> $OUTDIR/log.txt
    echo 'Status: 400 Bad Request'
    echo
    exit
fi

if [ ! -s $OUTDIR/${UUID}.svg  ] ;  then
    echo prov output SVG not found >> $OUTDIR/log.txt
    echo 'Status: 400 Bad Request'
    echo
    exit
fi

echo "Content-type: image/svg+xml"
echo ""
cat $OUTDIR/${UUID}.svg

exit 0

# to return link instead

cat << EOF
Content-Type: text/html

<!DOCTYPE html>
<html>
<head>
<title>Numbers Into Notes - Link to SVG File</title>
</head>
<body>
<h1>Link to SVG File</h1>
<p><a href="$URLBASE/${UUID}.svg" download>${UUID}</A> generated on $DATE</p>
</body>
</html>
EOF

echo Generated $URLBASE/${UUID}.svg >> $OUTDIR/log.txt

exit 0

# End of prov
